/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-03-24 17:51:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class autoQuote_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title>Auto Quote</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/imagehover.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/form-basic.css\"> \n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <!--Navigation bar-->\n");
      out.write("    <nav class=\"navbar navbar-default navbar-fixed-top\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <img src=\"img/logo.png\" alt=\"\" HEIGHT=\"70\" WIDTH=\"70\" BORDER=\"0\"/><a class=\"navbar-brand\" href=\"index.jsp\">Taylor<span>Insurance</span></a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                    <li class=\"btn-trial\"><a href=\"\" data-target=\"#login\" data-toggle=\"modal\">Login</a></li>\n");
      out.write("                    <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("                    <li><a href=\"homeQuote.jsp\">Get a Home Quote</a></li>\n");
      out.write("                    <li><a href=\"autoQuote.jsp\">Get an Auto Quote</a></li>\n");
      out.write("                    <li><a href=\"ContactUs.jsp\">Contact Us</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("    <!--End Nav -->\n");
      out.write("    <!--Modal box-->\n");
      out.write("    <div class=\"modal fade\" id=\"login\" role=\"dialog\">\n");
      out.write("        <div class=\"modal-dialog modal-sm\">\n");
      out.write("\n");
      out.write("            <!-- Modal content no 1-->\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                    <h4 class=\"modal-title text-center form-title\">Login</h4>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body padtrbl\">\n");
      out.write("\n");
      out.write("                    <form class=\"form-signin\" action=\"LoginServlet\">\n");
      out.write("                        <span id=\"reauth-email\" class=\"reauth-email\"></span>\n");
      out.write("                        <p class=\"input_title\">Email</p>\n");
      out.write("                        <input type=\"text\" name=\"inputEmail\" id=\"inputEmail\" class=\"login_box\" placeholder=\"Email\" required autofocus>\n");
      out.write("                        <p class=\"input_title\">Password</p>\n");
      out.write("                        <input type=\"password\" name=\"inputPassword\" id=\"inputPassword\" class=\"login_box\" placeholder=\"******\" required>\n");
      out.write("\n");
      out.write("                        <button class=\"btn btn-lg btn-primary\" type=\"submit\">Login</button>\n");
      out.write("                    </form><!-- /form -->\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!--/ Modal box-->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <body style=\"padding-top: 150px;\">\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <form class=\"form-horizontal\" action=\"AutoQuoteServlet\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <fieldset class=\"for-panel\">\n");
      out.write("                            <legend>Auto Quote</legend>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-sm-6\">\n");
      out.write("                                    <div class=\"form-horizontal\">               \n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">First Name: </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"firstName\" type=\"text\">     \n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Last Name: </label> \n");
      out.write("                                            <input class=\"form-control-static\" name=\"lastName\" type=\"text\"> \n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Email: </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"email\" type=\"email\">               \n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Street Address: </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"address\" type=\"text\"> \n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">City: </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"city\" type=\"text\">   \n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Province: </label>\n");
      out.write("                                            <select class=\"col-xs-5 control-label\" name=\"province\">\n");
      out.write("                                                <option>NL</option>\n");
      out.write("                                            </select>   \n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Country: </label>\n");
      out.write("                                            <select class=\"col-xs-5 control-label\" name=\"country\">\n");
      out.write("                                                <option>Canada</option>\n");
      out.write("                                            </select>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-sm-6\">\n");
      out.write("                                    <div class=\"form-horizontal\">               \n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Date of Birth: </label>\n");
      out.write("                                            <input class=\"form-control-static\" type=\"date\" name=\"phoneNumber\"> \n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">VIN: </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"vin\" type=\"text\">     \n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Make: </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"make\" type=\"text\">     \n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Model: </label> \n");
      out.write("                                            <input class=\"form-control-static\" name=\"model\" type=\"text\">   \n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\">Year: </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"year\" type=\"text\">              \n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\"><p>Number of Accidents</p> (Last 5 Years) </label>\n");
      out.write("                                            <input class=\"form-control-static\" name=\"accidents\">   \n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label class=\"col-xs-5 control-label\"></label>\n");
      out.write("                                            <button style=\"float: center;\" class=\"btn btn-primary\" type=\"submit\">Submit Home Quote</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </fieldset>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <!--Footer-->\n");
      out.write("        <footer id=\"footer\" class=\"footer\">\n");
      out.write("            <div class=\"container text-center\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <ul class=\"social-links\">\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-twitter fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-facebook fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-google-plus fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-dribbble fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-linkedin fa-fw\"></i></a></li>\n");
      out.write("                </ul>\n");
      out.write("                ©2017 Taylor Insurance\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!--/ Footer-->\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.easing.min.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/custom.js\"></script>\n");
      out.write("        <script src=\"contactform/contactform.js\"></script>\n");
      out.write("    </body>\n");
      out.write("    <style>\n");
      out.write("        footer { position:absolute; bottom:0;width:100%}\n");
      out.write("        fieldset.for-panel {\n");
      out.write("            background-color: #fcfcfc;\n");
      out.write("            border: 1px solid #999;\n");
      out.write("            border-radius: 4px;\t\n");
      out.write("            padding:15px 10px;\n");
      out.write("            background-color: #d9edf7;\n");
      out.write("            border-color: #bce8f1;\n");
      out.write("            background-color: #f9fdfd;\n");
      out.write("            margin-bottom:12px;\n");
      out.write("        }\n");
      out.write("        fieldset.for-panel legend {\n");
      out.write("            background-color: #fafafa;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            color: #4381ba;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            line-height: 10px;\n");
      out.write("            margin: inherit;\n");
      out.write("            padding: 7px;\n");
      out.write("            width: auto;\n");
      out.write("            background-color: #d9edf7;\n");
      out.write("            margin-bottom: 0;\n");
      out.write("        }\n");
      out.write("        input {\n");
      out.write("            display: block; /* add this */\n");
      out.write("            width: 250px;\n");
      out.write("            padding: 5px;\n");
      out.write("            -webkit-box-sizing: border-box; /* Safari/Chrome, other WebKit */\n");
      out.write("            -moz-box-sizing: border-box;    /* Firefox, other Gecko */\n");
      out.write("            box-sizing: border-box;         /* Opera/IE 8+ */\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
