/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-03-24 17:53:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title>Taylor Insurance</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/imagehover.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!--Navigation bar-->\n");
      out.write("        <nav class=\"navbar navbar-default navbar-fixed-top\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("                    </button>\n");
      out.write("                    <img src=\"img/logo.png\" alt=\"\" HEIGHT=\"70\" WIDTH=\"70\" BORDER=\"0\"/><a class=\"navbar-brand\" href=\"index.jsp\">Taylor<span>Insurance</span></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("                    <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                        <li><a href=\"#feature\">Our Services</a></li>\n");
      out.write("                        <li><a href=\"#team\">Our Team</a></li>\n");
      out.write("                        <li><a href=\"#testimonial\">Testimonials</a></li>\n");
      out.write("                        <li><a href=\"ContactUs.jsp\">Contact Us</a></li>\n");
      out.write("                        <li class=\"btn-trial\"><a href=\"\" data-target=\"#login\" data-toggle=\"modal\">Login</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!--/ Navigation bar-->\n");
      out.write("        <!--Modal box-->\n");
      out.write("        <div class=\"modal fade\" id=\"login\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog modal-sm\">\n");
      out.write("\n");
      out.write("                <!-- Modal content no 1-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                        <h4 class=\"modal-title text-center form-title\">Login</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body padtrbl\">\n");
      out.write("\n");
      out.write("                        <form class=\"form-signin\" action=\"LoginServlet\">\n");
      out.write("                            <span id=\"reauth-email\" class=\"reauth-email\"></span>\n");
      out.write("                            <p class=\"input_title\">Email</p>\n");
      out.write("                            <input type=\"text\" name=\"inputEmail\" id=\"inputEmail\" class=\"login_box\" placeholder=\"Email\" required autofocus>\n");
      out.write("                            <p class=\"input_title\">Password</p>\n");
      out.write("                            <input type=\"password\" name=\"inputPassword\" id=\"inputPassword\" class=\"login_box\" placeholder=\"******\" required>\n");
      out.write("\n");
      out.write("                            <button class=\"btn btn-lg btn-primary\" type=\"submit\">Login</button>\n");
      out.write("                        </form><!-- /form -->\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--/ Modal box-->\n");
      out.write("        <!--Banner-->\n");
      out.write("        <div class=\"banner\">\n");
      out.write("            <div class=\"bg-color\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"banner-text text-center\">\n");
      out.write("                            <div class=\"text-border\">\n");
      out.write("                                <h2 class=\"text-dec\">Small Town Customer Service</h2>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"intro-para text-center quote\">\n");
      out.write("                                <p class=\"big-text\">A Business of Caring</p>\n");
      out.write("                                <p class=\"small-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium enim repellat sapiente quos architecto<br>Laudantium enim repellat sapiente quos architecto</p>\n");
      out.write("                                <a href=\"homeQuote.jsp\"  class=\"btn\">GET A HOME QUOTE</a>\n");
      out.write("                                <a href=\"autoQuote.jsp\"  class=\"btn\">GET AN AUTO QUOTE</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--/ Banner-->\n");
      out.write("\n");
      out.write("        <!--Modal box 2-->\n");
      out.write("        <div class=\"modal fade\" id=\"quote\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog modal-sm\">\n");
      out.write("\n");
      out.write("                <!-- Modal content no 2-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" href=\"homeQuote.jsp\">&times;</button>\n");
      out.write("                        <h4 class=\"modal-title text-center form-title\">Get a Home Quote</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" href=\"autoQuote.jsp\">&times;</button>\n");
      out.write("                        <h4 class=\"modal-title text-center form-title\">Get an Auto Quote</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body padtrbl\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!--\n");
      out.write("                        <form class=\"form-signin\" action=\"\" method=\"POST\">\n");
      out.write("                            <span id=\"reauth-email\" class=\"reauth-email\"></span>\n");
      out.write("                            <p class=\"input_title\">Email</p>\n");
      out.write("                            <input type=\"text\" name=\"inputEmail\" id=\"inputEmail\" class=\"login_box\" placeholder=\"Email\" required autofocus>\n");
      out.write("                            <p class=\"input_title\">Password</p>\n");
      out.write("                            <input type=\"password\" name=\"inputPassword\" id=\"password\" class=\"login_box\" placeholder=\"******\" required>\n");
      out.write("                            <p class=\"input_title\">Confirm Password</p>\n");
      out.write("                            <input type=\"password\" name=\"inputPassword\" id=\"confirm_password\" class=\"login_box\" placeholder=\"******\" required>\n");
      out.write("                            <div id=\"remember\" class=\"checkbox\">\n");
      out.write("                                <label>\n");
      out.write("\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("                            <button class=\"btn btn-lg btn-primary\" type=\"submit\">Submit</button>\n");
      out.write("                        </form> /form -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--/ Modal box-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!---/ Services -->\n");
      out.write("        <section id =\"feature\" class=\"section-padding\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"header-section text-center\">\n");
      out.write("                        <h2>Our Services</h2>\n");
      out.write("                        <p>Insurance services that we provide</p>\n");
      out.write("                        <hr class=\"bottom-line\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"feature-info\">\n");
      out.write("                        <div class=\"fea\">\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <div class=\"heading pull-right\">\n");
      out.write("                                    <h4>Auto Insurance</h4>\n");
      out.write("                                    <p>Donec et lectus bibendum dolor dictum auctor in ac erat. Vestibulum egestas sollicitudin metus non urna in eros tincidunt convallis id id nisi in interdum.</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"fea-img pull-left\">\n");
      out.write("                                    <i class=\"fa fa-car\"></i>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"fea\">\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <div class=\"heading pull-right\">\n");
      out.write("                                    <h4>Home Insurance</h4>\n");
      out.write("                                    <p>Donec et lectus bibendum dolor dictum auctor in ac erat. Vestibulum egestas sollicitudin metus non urna in eros tincidunt convallis id id nisi in interdum.</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"fea-img pull-left\">\n");
      out.write("                                    <i class=\"fa fa-home\"></i>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"fea\">\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <div class=\"heading pull-right\">\n");
      out.write("                                    <h4>Customer Service</h4>\n");
      out.write("                                    <p>Donec et lectus bibendum dolor dictum auctor in ac erat. Vestibulum egestas sollicitudin metus non urna in eros tincidunt convallis id id nisi in interdum.</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"fea-img pull-left\">\n");
      out.write("                                    <i class=\"fa fa-trophy\"></i>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!--/ Services-->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--Our Team-->\n");
      out.write("        <section id=\"team\" class=\"section-padding\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"header-section text-center\">\n");
      out.write("                        <h2>Meet Our Team</h2>\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem nesciunt vitae,<br> maiores, magni dolorum aliquam.</p>\n");
      out.write("                        <hr class=\"bottom-line\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4 col-md-4 col-sm-4\">\n");
      out.write("                        <div class=\"pm-staff-profile-container\" >\n");
      out.write("                            <div class=\"pm-staff-profile-image-wrapper text-center\">\n");
      out.write("                                <div class=\"pm-staff-profile-image\">\n");
      out.write("                                    <img src=\"img/mentor.jpg\" alt=\"\" class=\"img-thumbnail img-circle\" />\n");
      out.write("                                </div>   \n");
      out.write("                            </div>                                \n");
      out.write("                            <div class=\"pm-staff-profile-details text-center\">  \n");
      out.write("                                <p class=\"pm-staff-profile-name\">Josh Taylor</p>\n");
      out.write("                                <p class=\"pm-staff-profile-title\">CEO/Owner</p>\n");
      out.write("\n");
      out.write("                                <p class=\"pm-staff-profile-bio\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et placerat dui. In posuere metus et elit placerat tristique. Maecenas eu est in sem ullamcorper tincidunt. </p>\n");
      out.write("                            </div>     \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4 col-md-4 col-sm-4\">\n");
      out.write("                        <div class=\"pm-staff-profile-container\" >\n");
      out.write("                            <div class=\"pm-staff-profile-image-wrapper text-center\">\n");
      out.write("                                <div class=\"pm-staff-profile-image\">\n");
      out.write("                                    <img src=\"img/mentor1.jpg\" alt=\"\" class=\"img-thumbnail img-circle\" />\n");
      out.write("                                </div>   \n");
      out.write("                            </div>                                \n");
      out.write("                            <div class=\"pm-staff-profile-details text-center\">  \n");
      out.write("                                <p class=\"pm-staff-profile-name\">Brent Furlong</p>\n");
      out.write("                                <p class=\"pm-staff-profile-title\">President</p>\n");
      out.write("\n");
      out.write("                                <p class=\"pm-staff-profile-bio\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et placerat dui. In posuere metus et elit placerat tristique. Maecenas eu est in sem ullamcorper tincidunt. </p>\n");
      out.write("                            </div>     \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4 col-md-4 col-sm-4\">\n");
      out.write("                        <div class=\"pm-staff-profile-container\" >\n");
      out.write("                            <div class=\"pm-staff-profile-image-wrapper text-center\">\n");
      out.write("                                <div class=\"pm-staff-profile-image\">\n");
      out.write("                                    <img src=\"img/mentor2.jpg\" alt=\"\" class=\"img-thumbnail img-circle\" />\n");
      out.write("                                </div>   \n");
      out.write("                            </div>                                \n");
      out.write("                            <div class=\"pm-staff-profile-details text-center\">  \n");
      out.write("                                <p class=\"pm-staff-profile-name\">Tim Bonnell</p>\n");
      out.write("                                <p class=\"pm-staff-profile-title\">Vice President </p>\n");
      out.write("\n");
      out.write("                                <p class=\"pm-staff-profile-bio\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et placerat dui. In posuere metus et elit placerat tristique. Maecenas eu est in sem ullamcorper tincidunt. </p>\n");
      out.write("                            </div>     \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!--/ team-->\n");
      out.write("\n");
      out.write("        <!--Testimonial-->\n");
      out.write("        <section id=\"testimonial\" class=\"section-padding\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"header-section text-center\">\n");
      out.write("                        <h2 class=\"white\">See What Our Customer Are Saying?</h2>\n");
      out.write("                        <p class=\"white\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem nesciunt vitae,<br> maiores, magni dolorum aliquam.</p>\n");
      out.write("                        <hr class=\"bottom-line bg-white\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"text-comment\">\n");
      out.write("                            <p class=\"text-par\">\"Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, nec sagittis sem\"</p>\n");
      out.write("                            <p class=\"text-name\">Abraham Doe - Creative Dırector</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"text-comment\">\n");
      out.write("                            <p class=\"text-par\">\"Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, nec sagittis sem\"</p>\n");
      out.write("                            <p class=\"text-name\">Abraham Doe - Creative Dırector</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!--/ Testimonial-->\n");
      out.write("\n");
      out.write("       \n");
      out.write("        <!--Footer-->\n");
      out.write("        <footer id=\"footer\" class=\"footer\">\n");
      out.write("            <div class=\"container text-center\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <ul class=\"social-links\">\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-twitter fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-facebook fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-google-plus fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-dribbble fa-fw\"></i></a></li>\n");
      out.write("                    <li><a href=\"#link\"><i class=\"fa fa-linkedin fa-fw\"></i></a></li>\n");
      out.write("                </ul>\n");
      out.write("                ©2017 Taylor Insurance\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!--/ Footer-->\n");
      out.write("\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.easing.min.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/custom.js\"></script>\n");
      out.write("        <script src=\"contactform/contactform.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            var password = document.getElementById(\"password\")\n");
      out.write("                    , confirm_password = document.getElementById(\"confirm_password\");\n");
      out.write("\n");
      out.write("            function validatePassword() {\n");
      out.write("                if (password.value != confirm_password.value) {\n");
      out.write("                    confirm_password.setCustomValidity(\"Passwords Don't Match\");\n");
      out.write("                } else {\n");
      out.write("                    confirm_password.setCustomValidity('');\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            password.onchange = validatePassword;\n");
      out.write("            confirm_password.onkeyup = validatePassword;\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
